channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=23.1.2
- pip:
  - mlflow==2.4
  - cloudpickle==2.0.0
  - importlib-metadata==4.11.3
  - numpy==1.21.5
  - psutil==5.8.0
  - scikit-learn==1.0.2
  - scipy==1.7.3
name: mlflow-env
